 **Mathematical & Statistical Operations**

In [ ]:
import numpy as np

np.random.seed(42)

# Simulated dataset: 5 students, 4 subjects
scores = np.array([
    [85, 90, 78, 92],   # Student 0
    [70, 65, 88, 74],   # Student 1
    [95, 80, 72, 91],   # Student 2
    [60, 75, 85, 68],   # Student 3
    [88, 92, 79, 96],   # Student 4
])
subjects = ["Math", "Science", "English", "History"]
print("Score Matrix (5 students × 4 subjects):")
print(scores, "\n")

Score Matrix (5 students × 4 subjects):
[[85 90 78 92]
 [70 65 88 74]
 [95 80 72 91]
 [60 75 85 68]
 [88 92 79 96]] 



 ELEMENT-WISE ARITHMETIC

In [ ]:
print("═══ Element-wise Arithmetic ═══")
a = np.array([10, 20, 30, 40])
b = np.array([1,  2,  3,  4])

print(f"a + b   = {a + b}")
print(f"a - b   = {a - b}")
print(f"a * b   = {a * b}")
print(f"a / b   = {a / b}")
print(f"a ** 2  = {a ** 2}")
print(f"a % 3   = {a % 3}")
print(f"a // 3  = {a // 3}\n")

═══ Element-wise Arithmetic ═══
a + b   = [11 22 33 44]
a - b   = [ 9 18 27 36]
a * b   = [ 10  40  90 160]
a / b   = [10. 10. 10. 10.]
a ** 2  = [ 100  400  900 1600]
a % 3   = [1 2 0 1]
a // 3  = [ 3  6 10 13]



UNIVERSAL FUNCTIONS

In [ ]:
print("═══ Universal Functions ═══")
angles = np.array([0, np.pi / 6, np.pi / 4, np.pi / 3, np.pi / 2])

print(f"sqrt(a)     = {np.sqrt(a)}")
print(f"exp([1,2,3])= {np.exp([1, 2, 3])}")
print(f"log(a)      = {np.log(a)}")
print(f"sin(angles) = {np.round(np.sin(angles), 4)}")
print(f"cos(angles) = {np.round(np.cos(angles), 4)}")
print(f"abs([-3,4]) = {np.abs([-3, 4])}\n")

═══ Universal Functions ═══
sqrt(a)     = [3.16227766 4.47213595 5.47722558 6.32455532]
exp([1,2,3])= [ 2.71828183  7.3890561  20.08553692]
log(a)      = [2.30258509 2.99573227 3.40119738 3.68887945]
sin(angles) = [0.     0.5    0.7071 0.866  1.    ]
cos(angles) = [1.     0.866  0.7071 0.5    0.    ]
abs([-3,4]) = [3 4]



 AGGREGATION — FULL ARRAY

In [ ]:
print("═══ Full-Array Aggregation ═══")
print(f"Sum of all scores   : {np.sum(scores)}")
print(f"Min score           : {np.min(scores)}")
print(f"Max score           : {np.max(scores)}")
print(f"Mean score          : {np.mean(scores):.2f}")
print(f"Median score        : {np.median(scores):.2f}")
print(f"Std deviation       : {np.std(scores):.2f}")
print(f"Variance            : {np.var(scores):.2f}\n")

═══ Full-Array Aggregation ═══
Sum of all scores   : 1623
Min score           : 60
Max score           : 96
Mean score          : 81.15
Median score        : 82.50
Std deviation       : 10.35
Variance            : 107.03



 AXIS-WISE OPERATIONS

In [ ]:
print("═══ Axis-wise Operations ═══")
print("  axis=0 → down rows (per subject)")
print("  axis=1 → across columns (per student)\n")

# Per subject (column-wise)
subject_means = np.mean(scores, axis=0)
print("Mean per subject :", dict(zip(subjects, np.round(subject_means, 2))))

subject_max = np.max(scores, axis=0)
print("Max per subject  :", dict(zip(subjects, subject_max)))

# Per student (row-wise)
student_means = np.mean(scores, axis=1)
print(f"\nMean per student : {np.round(student_means, 2)}")

student_totals = np.sum(scores, axis=1)
print(f"Total per student: {student_totals}")

# Cumulative sum per student
print(f"\nCumulative sum (axis=1):\n{np.cumsum(scores, axis=1)}\n")


═══ Axis-wise Operations ═══
  axis=0 → down rows (per subject)
  axis=1 → across columns (per student)

Mean per subject : {'Math': np.float64(79.6), 'Science': np.float64(80.4), 'English': np.float64(80.4), 'History': np.float64(84.2)}
Max per subject  : {'Math': np.int64(95), 'Science': np.int64(92), 'English': np.int64(88), 'History': np.int64(96)}

Mean per student : [86.25 74.25 84.5  72.   88.75]
Total per student: [345 297 338 288 355]

Cumulative sum (axis=1):
[[ 85 175 253 345]
 [ 70 135 223 297]
 [ 95 175 247 338]
 [ 60 135 220 288]
 [ 88 180 259 355]]



SORTING & SEARCHING

In [ ]:
print("═══ Sorting & Searching ═══")

flat = np.array([42, 11, 88, 3, 55, 27])
print(f"Original       : {flat}")
print(f"Sorted         : {np.sort(flat)}")
print(f"Argsort (idx)  : {np.argsort(flat)}")

# Sort each student's scores
print(f"\nScores sorted per student (axis=1):\n{np.sort(scores, axis=1)}")

# Find indices where condition is true
print(f"\nIndices where flat > 30: {np.where(flat > 30)}")
print(f"Values where flat > 30: {flat[flat > 30]}")

# argmin / argmax
print(f"\nBest student (highest mean) : Student {np.argmax(student_means)}")
print(f"Hardest subject (lowest mean): {subjects[np.argmin(subject_means)]}")



═══ Sorting & Searching ═══
Original       : [42 11 88  3 55 27]
Sorted         : [ 3 11 27 42 55 88]
Argsort (idx)  : [3 1 5 0 4 2]

Scores sorted per student (axis=1):
[[78 85 90 92]
 [65 70 74 88]
 [72 80 91 95]
 [60 68 75 85]
 [79 88 92 96]]

Indices where flat > 30: (array([0, 2, 4]),)
Values where flat > 30: [42 88 55]

Best student (highest mean) : Student 4
Hardest subject (lowest mean): Math


 RESHAPING

In [2]:
import numpy as np

In [3]:
print("═══ Reshaping ═══")

arr = np.arange(1, 13)   # [1, 2, 3, ..., 12]
print(f"Original (1-D, 12 elements): {arr}\n")

# reshape to different dimensions
reshaped_3x4 = arr.reshape(3, 4)
reshaped_4x3 = arr.reshape(4, 3)
reshaped_2x2x3 = arr.reshape(2, 2, 3)

print(f"reshape(3, 4):\n{reshaped_3x4}\n")
print(f"reshape(4, 3):\n{reshaped_4x3}\n")
print(f"reshape(2, 2, 3) — 3-D:\n{reshaped_2x2x3}\n")

# Using -1 for automatic dimension inference
auto_shape = arr.reshape(3, -1)   # NumPy infers 4 columns
print(f"reshape(3, -1) → shape {auto_shape.shape}:\n{auto_shape}\n")

═══ Reshaping ═══
Original (1-D, 12 elements): [ 1  2  3  4  5  6  7  8  9 10 11 12]

reshape(3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

reshape(4, 3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

reshape(2, 2, 3) — 3-D:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

reshape(3, -1) → shape (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



FLATTEN vs RAVEL

In [4]:
print("═══ Flatten vs Ravel ═══")

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

flat_copy = matrix.flatten()    # returns a COPY
flat_view = matrix.ravel()      # returns a VIEW

print(f"flatten() : {flat_copy}  (copy)")
print(f"ravel()   : {flat_view}  (view)\n")

# Prove ravel is a view
flat_view[0] = 99
print(f"After ravel()[0] = 99 → matrix[0,0] = {matrix[0, 0]}")
matrix[0, 0] = 1  # reset

═══ Flatten vs Ravel ═══
flatten() : [1 2 3 4 5 6]  (copy)
ravel()   : [1 2 3 4 5 6]  (view)

After ravel()[0] = 99 → matrix[0,0] = 99


 TRANSPOSE

In [5]:
print("\n═══ Transpose ═══")

mat = np.arange(1, 7).reshape(2, 3)
print(f"Original (2×3):\n{mat}")
print(f"Transposed (3×2):\n{mat.T}")
print(f"Using np.transpose:\n{np.transpose(mat)}\n")

# Swap axes in 3-D
cube = np.arange(24).reshape(2, 3, 4)
print(f"3-D shape        : {cube.shape}")
print(f"swapaxes(0, 2)   : {np.swapaxes(cube, 0, 2).shape}\n")



═══ Transpose ═══
Original (2×3):
[[1 2 3]
 [4 5 6]]
Transposed (3×2):
[[1 4]
 [2 5]
 [3 6]]
Using np.transpose:
[[1 4]
 [2 5]
 [3 6]]

3-D shape        : (2, 3, 4)
swapaxes(0, 2)   : (4, 3, 2)



 STACKING & SPLITTING

In [6]:
print("═══ Stacking & Splitting ═══")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking
print(f"hstack : {np.hstack([a, b])}")            # [1,2,3,4,5,6]
print(f"vstack :\n{np.vstack([a, b])}")            # 2×3
print(f"column_stack:\n{np.column_stack([a, b])}")  # 3×2
print(f"dstack shape: {np.dstack([a, b]).shape}")   # 1×3×2

# Concatenation
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
print(f"\nconcat axis=0:\n{np.concatenate([c, d], axis=0)}")  # 4×2
print(f"concat axis=1:\n{np.concatenate([c, d], axis=1)}")    # 2×4

# Splitting
big = np.arange(12).reshape(3, 4)
print(f"\nOriginal:\n{big}")
splits = np.hsplit(big, 2)   # split into 2 along columns
print(f"hsplit into 2:")
for i, s in enumerate(splits):
    print(f"  Part {i}: {s.shape}\n{s}")

vsplits = np.vsplit(big, 3)  # split into 3 along rows
print(f"vsplit into 3: {[s.shape for s in vsplits]}\n")


═══ Stacking & Splitting ═══
hstack : [1 2 3 4 5 6]
vstack :
[[1 2 3]
 [4 5 6]]
column_stack:
[[1 4]
 [2 5]
 [3 6]]
dstack shape: (1, 3, 2)

concat axis=0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
concat axis=1:
[[1 2 5 6]
 [3 4 7 8]]

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
hsplit into 2:
  Part 0: (3, 2)
[[0 1]
 [4 5]
 [8 9]]
  Part 1: (3, 2)
[[ 2  3]
 [ 6  7]
 [10 11]]
vsplit into 3: [(1, 4), (1, 4), (1, 4)]



 BROADCASTING

In [7]:
print("═══ Broadcasting ═══")
print("""
Broadcasting rules:
  1. If arrays differ in ndim, the smaller is padded with 1s on the left.
  2. Arrays with size 1 in a dimension act as if they had the size of
     the largest array in that dimension.
  3. If sizes disagree and neither is 1 → error.
""")

# Example 1: scalar + array
print("--- Scalar + Array ---")
arr = np.array([10, 20, 30])
result = arr + 5
print(f"[10, 20, 30] + 5 = {result}\n")

# Example 2: 1-D + 2-D (row broadcast)
print("--- Row Broadcast ---")
matrix = np.ones((3, 3)) * 10
row = np.array([1, 2, 3])
print(f"Matrix (3×3):\n{matrix}")
print(f"Row    (3,) : {row}")
print(f"Matrix + Row:\n{matrix + row}\n")

# Example 3: Column broadcast
print("--- Column Broadcast ---")
col = np.array([[100], [200], [300]])  # shape (3,1)
print(f"Col (3×1):\n{col}")
print(f"Matrix + Col:\n{matrix + col}\n")

# Example 4: Outer operation via broadcasting
print("--- Outer Product via Broadcasting ---")
x = np.array([1, 2, 3])          # shape (3,)
y = np.array([[10], [20], [30]])  # shape (3,1)
outer = x * y                    # shape (3,3)
print(f"x = {x}")
print(f"y =\n{y}")
print(f"x * y (outer product):\n{outer}\n")

# Example 5: Practical — Normalising columns (zero-mean, unit-std)
print("--- Practical: Column Normalisation ---")
data = np.array([[170, 65, 25],
                 [180, 80, 30],
                 [160, 55, 22],
                 [175, 70, 28]], dtype=float)
labels = ["Height", "Weight", "Age"]

col_mean = data.mean(axis=0)   # shape (4,) broadcasted over rows
col_std  = data.std(axis=0)

normalised = (data - col_mean) / col_std
print(f"Original:\n{data}")
print(f"Means : {col_mean}")
print(f"Stds  : {np.round(col_std, 2)}")
print(f"Normalised:\n{np.round(normalised, 2)}")



═══ Broadcasting ═══

Broadcasting rules:
  1. If arrays differ in ndim, the smaller is padded with 1s on the left.
  2. Arrays with size 1 in a dimension act as if they had the size of
     the largest array in that dimension.
  3. If sizes disagree and neither is 1 → error.

--- Scalar + Array ---
[10, 20, 30] + 5 = [15 25 35]

--- Row Broadcast ---
Matrix (3×3):
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
Row    (3,) : [1 2 3]
Matrix + Row:
[[11. 12. 13.]
 [11. 12. 13.]
 [11. 12. 13.]]

--- Column Broadcast ---
Col (3×1):
[[100]
 [200]
 [300]]
Matrix + Col:
[[110. 110. 110.]
 [210. 210. 210.]
 [310. 310. 310.]]

--- Outer Product via Broadcasting ---
x = [1 2 3]
y =
[[10]
 [20]
 [30]]
x * y (outer product):
[[10 20 30]
 [20 40 60]
 [30 60 90]]

--- Practical: Column Normalisation ---
Original:
[[170.  65.  25.]
 [180.  80.  30.]
 [160.  55.  22.]
 [175.  70.  28.]]
Means : [171.25  67.5   26.25]
Stds  : [7.4  9.01 3.03]
Normalised:
[[-0.17 -0.28 -0.41]
 [ 1.18  1.39  1.24]
 [-1.52

Save & Load Operations

In [12]:
import numpy as np
import os
# Create an output directory for saved files
SAVE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "saved_arrays")
os.makedirs(SAVE_DIR, exist_ok=True)
print(f"Save directory: {SAVE_DIR}\n")


In [13]:
scores = np.array([
    [85, 90, 78, 92],
    [70, 65, 88, 74],
    [95, 80, 72, 91],
])
labels = np.array(["Alice", "Bob", "Charlie"])


# ─── 1. BINARY FORMAT — .npy (single array) ─────────────────

print("═══ 1. np.save / np.load (.npy) ═══")

filepath = os.path.join(SAVE_DIR, "scores.npy")
np.save(filepath, scores)
print(f"Saved scores to {filepath}")

loaded_scores = np.load(filepath)
print(f"Loaded scores:\n{loaded_scores}")
print(f"Arrays equal: {np.array_equal(scores, loaded_scores)}\n")


# ─── 2. MULTIPLE ARRAYS — .npz ──────────────────────────────

print("═══ 2. np.savez / np.savez_compressed (.npz) ═══")

# Uncompressed
filepath_npz = os.path.join(SAVE_DIR, "data_bundle.npz")
np.savez(filepath_npz, scores=scores, labels=labels)
print(f"Saved bundle to {filepath_npz}")

bundle = np.load(filepath_npz, allow_pickle=True)
print(f"Keys in bundle   : {list(bundle.keys())}")
print(f"bundle['scores'] :\n{bundle['scores']}")
print(f"bundle['labels'] : {bundle['labels']}\n")

# Compressed (smaller file size)
filepath_compressed = os.path.join(SAVE_DIR, "data_compressed.npz")
np.savez_compressed(filepath_compressed, scores=scores, labels=labels)

size_uncompressed = os.path.getsize(filepath_npz)
size_compressed   = os.path.getsize(filepath_compressed)
print(f"Uncompressed size: {size_uncompressed} bytes")
print(f"Compressed size  : {size_compressed} bytes")
print(f"Saved {size_uncompressed - size_compressed} bytes with compression\n")


═══ 1. np.save / np.load (.npy) ═══


NameError: name 'SAVE_DIR' is not defined

In [ ]:

print("═══ 3. np.savetxt / np.loadtxt (.csv / .txt) ═══")

# Save as CSV (human-readable)
filepath_csv = os.path.join(SAVE_DIR, "scores.csv")
np.savetxt(filepath_csv, scores,
           delimiter=",",
           header="Math,Science,English,History",
           fmt="%d",
           comments="")
print(f"Saved CSV to {filepath_csv}")

# Print CSV contents
with open(filepath_csv, "r") as f:
    print(f"CSV contents:\n{f.read()}")

# Load from CSV
loaded_csv = np.loadtxt(filepath_csv, delimiter=",", skiprows=1)
print(f"Loaded from CSV:\n{loaded_csv}")
print(f"dtype: {loaded_csv.dtype}\n")


# ─── 4. HANDLING MISSING DATA — np.genfromtxt ───────────────

print("═══ 4. np.genfromtxt (missing data) ═══")

# Create a CSV with missing values
filepath_missing = os.path.join(SAVE_DIR, "incomplete_data.csv")
with open(filepath_missing, "w") as f:
    f.write("Height,Weight,Age\n")
    f.write("170,65,25\n")
    f.write("180,,30\n")        # missing weight
    f.write(",55,22\n")         # missing height
    f.write("175,70,\n")        # missing age

print(f"Created CSV with missing values at {filepath_missing}")
print("CSV contents:")
with open(filepath_missing, "r") as f:
    print(f.read())

# Load with genfromtxt — missing values become NaN
data = np.genfromtxt(filepath_missing, delimiter=",",
                     skip_header=1, filling_values=np.nan)
print(f"Loaded with genfromtxt (NaN for missing):\n{data}")
print(f"dtype: {data.dtype}\n")

# Replace NaN with column means
col_means = np.nanmean(data, axis=0)
print(f"Column means (ignoring NaN): {np.round(col_means, 2)}")

nan_mask = np.isnan(data)
for col in range(data.shape[1]):
    data[nan_mask[:, col], col] = col_means[col]

print(f"After filling NaN with column means:\n{np.round(data, 1)}")


# ─── 5. SUMMARY OF FORMATS ──────────────────────────────────

print("\n═══ Format Comparison ═══")
print(f"{'Format':<20} {'Extension':<10} {'Human Readable':<16} {'Multi-Array':<12} {'Compressed'}")
print("-" * 72)
print(f"{'np.save/load':<20} {'.npy':<10} {'No':<16} {'No':<12} {'No'}")
print(f"{'np.savez':<20} {'.npz':<10} {'No':<16} {'Yes':<12} {'No'}")
print(f"{'np.savez_compressed':<20} {'.npz':<10} {'No':<16} {'Yes':<12} {'Yes'}")
print(f"{'np.savetxt/loadtxt':<20} {'.csv/.txt':<10} {'Yes':<16} {'No':<12} {'No'}")
print(f"{'np.genfromtxt':<20} {'.csv/.txt':<10} {'Yes':<16} {'No':<12} {'No'}")



 Performance: NumPy vs Python Lists

In [14]:
import numpy as np
import time
import sys

def benchmark(label, func, *args, runs=5):
    """Run a function multiple times and return avg time in ms."""
    times = []
    for _ in range(runs):
        start = time.perf_counter()
        result = func(*args)
        end = time.perf_counter()
        times.append((end - start) * 1000)
    avg = sum(times) / len(times)
    print(f"  {label:<35}: {avg:>8.3f} ms  (avg of {runs} runs)")
    return avg


SIZE = 1_000_000
print(f"═══ Performance Comparison: NumPy vs Python Lists ═══")
print(f"Array / List size: {SIZE:,}\n")

═══ Performance Comparison: NumPy vs Python Lists ═══
Array / List size: 1,000,000



 CREATION

In [ ]:
print("─── 1. Creation ───")
t_list = benchmark("Python list (range)",
                    lambda: list(range(SIZE)))
t_np   = benchmark("NumPy arange",
                    lambda: np.arange(SIZE))
print(f"  → NumPy is {t_list / t_np:.1f}× faster\n")

ELEMENT-WISE MULTIPLICATION

In [15]:

print("─── 2. Element-wise Multiply (× 2) ───")
py_list = list(range(SIZE))
np_arr  = np.arange(SIZE)

t_list = benchmark("Python list comprehension",
                    lambda: [x * 2 for x in py_list])
t_np   = benchmark("NumPy vectorised",
                    lambda: np_arr * 2)
print(f"  → NumPy is {t_list / t_np:.1f}× faster\n")

─── 2. Element-wise Multiply (× 2) ───
  Python list comprehension          :   72.121 ms  (avg of 5 runs)
  NumPy vectorised                   :    2.959 ms  (avg of 5 runs)
  → NumPy is 24.4× faster



 SUM

In [ ]:

print("─── 3. Summation ───")
t_list = benchmark("Python sum()",
                    lambda: sum(py_list))
t_np   = benchmark("NumPy np.sum()",
                    lambda: np.sum(np_arr))
print(f"  → NumPy is {t_list / t_np:.1f}× faster\n"

FILTERING (BOOLEAN)

In [ ]:
print("─── 5. Boolean Filtering (> 500,000) ───")
t_list = benchmark("Python list comprehension",
                    lambda: [x for x in py_list if x > 500_000])
t_np   = benchmark("NumPy boolean indexing",
                    lambda: np_arr[np_arr > 500_000])
print(f"  → NumPy is {t_list / t_np:.1f}× faster\n")

MEMORY COMPARISON

In [16]:
print("─── 6. Memory Usage ───")
py_mem     = sys.getsizeof(py_list) + sys.getsizeof(py_list[0]) * len(py_list)
np_mem     = np_arr.nbytes

print(f"  Python list : {py_mem / 1e6:.2f} MB")
print(f"  NumPy array : {np_mem / 1e6:.2f} MB")
print(f"  → NumPy uses {py_mem / np_mem:.1f}× less memory\n")

─── 6. Memory Usage ───
  Python list : 36.00 MB
  NumPy array : 8.00 MB
  → NumPy uses 4.5× less memory

